name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main  # or master, depending on your branch

jobs:
  ftp-deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        #local-dir: C:\Users\the13thGod\Documents\Projects\steerhubit\steerhubit\ # Root directory of your repo
        server-dir: /public_html
